/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Password;

import javax.swing.JOptionPane;

/**
 *
 * @author pared
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    Password persona;
    public Principal() {
        initComponents();
        cmbBorrar.setEnabled(false);
        cmbCambiarContraseña.setEnabled(false);
        cmbCrear.setEnabled(true);
        cmbMostrar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        cmbCrear = new javax.swing.JButton();
        cmbBorrar = new javax.swing.JButton();
        cmbCambiarContraseña = new javax.swing.JButton();
        cmbMostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMostrar = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("PASSWORD");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Ingrese Contraseña:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 20));
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 110, -1));

        cmbCrear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbCrear.setText("Crear");
        cmbCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCrearActionPerformed(evt);
            }
        });
        jPanel1.add(cmbCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 130, -1));

        cmbBorrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbBorrar.setText("Borrar");
        cmbBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(cmbBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 130, -1));

        cmbCambiarContraseña.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbCambiarContraseña.setText("Cambiar Contraseña");
        cmbCambiarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCambiarContraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(cmbCambiarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, -1));

        cmbMostrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbMostrar.setText("Mostrar");
        cmbMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMostrarActionPerformed(evt);
            }
        });
        jPanel1.add(cmbMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 130, -1));

        txtMostrar.setColumns(20);
        txtMostrar.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        txtMostrar.setRows(5);
        jScrollPane1.setViewportView(txtMostrar);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 200, 120));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCrearActionPerformed
        // TODO add your handling code here:
        String contraseña;
        if (txtPassword.getText().trim().isEmpty())
        {
           JOptionPane.showMessageDialog(this, "Ingrese la contraseña", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else 
        {
        contraseña= (txtPassword.getText());
        persona = new Password (contraseña);
        
        JOptionPane.showMessageDialog(this, persona.Validar());
        }
        
        cmbCrear.setEnabled(true);
        cmbMostrar.setEnabled(true);
        cmbCambiarContraseña.setEnabled(true);
        cmbBorrar.setEnabled(true);
    }//GEN-LAST:event_cmbCrearActionPerformed

    private void cmbCambiarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCambiarContraseñaActionPerformed
        // TODO add your handling code here:
        int op;
        op = JOptionPane.showConfirmDialog(this, "¿Esta seguro que desea cambiar la contraeña=", "Aviso", JOptionPane.YES_OPTION);
        if (op == JOptionPane.YES_OPTION)
        {
        txtPassword.setText("");
        txtMostrar.setText("");
        txtPassword.requestFocusInWindow();
        String contraseña2;
        contraseña2= (txtPassword.getText());
        persona.CambiarContraseña(contraseña2);
        
        cmbMostrar.setEnabled(false);
        cmbCrear.setEnabled(true);
        cmbBorrar.setEnabled(false);
        cmbCambiarContraseña.setEnabled(false);
        }
    }//GEN-LAST:event_cmbCambiarContraseñaActionPerformed

    private void cmbMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMostrarActionPerformed
        // TODO add your handling code here:
        String aux;
        aux = persona.mostrar();
        txtMostrar.setText(aux);
        
        cmbBorrar.setEnabled(true);
        cmbCambiarContraseña.setEnabled(true);
        cmbCrear.setEnabled(false);
        cmbMostrar.setEnabled(false);
    }//GEN-LAST:event_cmbMostrarActionPerformed

    private void cmbBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBorrarActionPerformed
        // TODO add your handling code here:
        txtPassword.setText("");
        txtMostrar.setText("");
        txtMostrar.requestFocusInWindow();
        
        cmbBorrar.setEnabled(true);
        cmbCambiarContraseña.setEnabled(false);
        cmbCrear.setEnabled(true);
        cmbMostrar.setEnabled(false);
    }//GEN-LAST:event_cmbBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmbBorrar;
    private javax.swing.JButton cmbCambiarContraseña;
    private javax.swing.JButton cmbCrear;
    private javax.swing.JButton cmbMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtMostrar;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
