/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Password;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author pared
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    ArrayList<Password> v = new ArrayList();
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        txtSeguridad = new javax.swing.JTextField();
        cmbMostrar = new javax.swing.JButton();
        cmbBorrar = new javax.swing.JButton();
        cmbCambiarContraseña = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("PASSWORD");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Ingrese Contraseña:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 20));
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 110, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Seguridad de Contraseña:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        txtSeguridad.setEditable(false);
        jPanel1.add(txtSeguridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 70, -1));

        cmbMostrar.setText("Crear");
        cmbMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMostrarActionPerformed(evt);
            }
        });
        jPanel1.add(cmbMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 90, -1));

        cmbBorrar.setText("Borrar");
        jPanel1.add(cmbBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 90, -1));

        cmbCambiarContraseña.setText("Cambiar Contraseña");
        cmbCambiarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCambiarContraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(cmbCambiarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMostrarActionPerformed
        // TODO add your handling code here:
        String longitud;
        String contraseña;
        Password aux;
        Password usuario;
        contraseña= (txtPassword.getText());
        usuario = new Password (contraseña);
        
        txtSeguridad.setText(""+usuario.mostrar());
        
    }//GEN-LAST:event_cmbMostrarActionPerformed

    private void cmbCambiarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCambiarContraseñaActionPerformed
        // TODO add your handling code here:
        int op;
        
        op= JOptionPane.showConfirmDialog(this, "¿Esta seguro que la desea cambiar?", "Pregunta", JOptionPane.YES_OPTION);
        if (op == JOptionPane.YES_OPTION){
        String longitud; String contraseña;
        Password usuario, aux;
        
        contraseña= JOptionPane.showInputDialog("Ingrese la nueva contraseña");
        longitud= (contraseña);
        
        usuario = new Password (contraseña);
        aux= usuario.CambiarContraseña(usuario);
        if (longitud.length()<6)
        {
            txtSeguridad.setText("Debil");
        }
        else if (longitud.length()>8)
        {
            JOptionPane.showMessageDialog(this, "La contraseña no puede ser mayor de 8 caracteres", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        if (longitud.length()>=6 && longitud.length()<8)
        {
            txtPassword.setText(""+aux.getContraseña());
            txtSeguridad.setText("Fuerte");
            JOptionPane.showMessageDialog(this, "Contraseña Creada Correctamente");
        }
        }
    }//GEN-LAST:event_cmbCambiarContraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmbBorrar;
    private javax.swing.JButton cmbCambiarContraseña;
    private javax.swing.JButton cmbMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtSeguridad;
    // End of variables declaration//GEN-END:variables
}
